/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 09:27:58 GMT 2024
 */

package Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Controller.ControladorEncomenda;
import Model.Vintage;
import View.Apresentacao;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControladorEncomenda_ESTest extends ControladorEncomenda_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.removerArtigo((Apresentacao) null, (List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Vintage vintage0 = mock(Vintage.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(vintage0).encomendasParaDevolver();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretadorDevolver((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Vintage vintage0 = mock(Vintage.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(vintage0).encomendasParaDevolver();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretadorAdiar((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Vintage vintage0 = mock(Vintage.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(vintage0).getArtigosVenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretador((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.adicionarArtigo((Apresentacao) null, (List<Integer>) null, (List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = mock(Apresentacao.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        controladorEncomenda0.removerArtigo(apresentacao0, (List<Integer>) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ControladorEncomenda controladorEncomenda0 = new ControladorEncomenda();
      Apresentacao apresentacao0 = mock(Apresentacao.class, new ViolatedAssumptionAnswer());
      Apresentacao apresentacao1 = mock(Apresentacao.class, new ViolatedAssumptionAnswer());
      Vintage vintage0 = mock(Vintage.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(vintage0).getArtigosVenda();
      // Undeclared exception!
      try { 
        controladorEncomenda0.interpretador(apresentacao1, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorEncomenda", e);
      }
  }
}
